clean ${PAI_WORK_DIR} before mv content to this folder (#3695)
* clean ${PAI_WORK_DIR} before mv content to this folder

In prod env, we saw when node down and up. The pod running on this node
may be restarted by kubelet. Even though the `restartPolicy` set to
`Never`. If that happens, the init container script will failed when
executing `mv` command. To prevent this, we clean the `${PAI_WORK_DIR}`
before mv content to this folder.

* fix review comments

* fix

* fix review comment

* add log

diff --git a/src/kube-runtime/src/init b/src/kube-runtime/src/init
--- a/src/kube-runtime/src/init
+++ b/src/kube-runtime/src/init
@@ -20,9 +20,16 @@
 set -o errexit
 set -o nounset
 set -o pipefail
+set -x
 
 CHILD_PROCESS="UNKNOWN"
 
+# exit code map
+# FRAMEWORK_BARRIER: 200 -> 250 FrameworkBarrierTransientFailed
+#                    201 -> 251 JobGangAllocationTimeout
+#                    210 -> 252 FrameworkBarrierPermanentFailed
+# PORT_CONFLICT_CHECKER: 10 -> 253 ContainerPortConflict
+# PAIRuntimeInitContainerUnkownError: 248
 function exit_handler()
 {
   EXIT_CODE=$?
@@ -53,14 +60,15 @@ function exit_handler()
   fi
 
   # signal triggered, do not change exit code
-  if [[ $EXIT_CODE -eq 130 || $EXIT_CODE -eq 131 || $EXIT_CODE -eq 132 || \
-        $EXIT_CODE -eq 134 || $EXIT_CODE -eq 135 || $EXIT_CODE -eq 136 || \
-        $EXIT_CODE -eq 137 || $EXIT_CODE -eq 139 || $EXIT_CODE -eq 141 || $EXIT_CODE -eq 143 ]]; then
-    exit $EXIT_CODE
-  fi
-
-  echo "Unknown exit code, platform error"
-  exit 1
+  case $EXIT_CODE in
+    130|131|132|134|135|136|137|139|141|143)
+      exit $EXIT_CODE
+      ;;
+    *)
+      echo "Unknown exit code, platform error"
+      exit 248
+      ;;
+  esac
 }
 
 trap exit_handler EXIT
@@ -77,6 +85,23 @@ PAI_INIT_DIR=${PAI_WORK_DIR}/init.d
 PAI_RUNTIME_DIR=${PAI_WORK_DIR}/runtime.d
 
 PAI_LOG_DIR=${PAI_WORK_DIR}/logs/${FC_POD_UID}
+
+# Move previous logs to another folder. Notice: for init.log, some part will append to previous log file
+LOG_FILES=$(find $PAI_LOG_DIR -maxdepth 1 -type f)
+if [[ ! -z $LOG_FILES ]]; then
+  echo "[WARN] $PAI_LOG_DIR not empty, contains previous results"
+  RANDOM=$$
+  PRE_LOG_DIR=$PAI_LOG_DIR/prelog_$RANDOM
+  while [[ -d PRE_LOG_DIR=$PAI_LOG_DIR/prelog_$RANDOM ]]
+  do
+    PRE_LOG_DIR=$PAI_LOG_DIR/prelog_$RANDOM
+  done
+  mkdir $PRE_LOG_DIR
+  mv $LOG_FILES $PRE_LOG_DIR
+fi
+
+# Clean ${PAI_WORK_DIR} since it may contain last execution content. (rarely happen, but seen in real world)
+rm -rf ${PAI_WORK_DIR}/*
 
 # Move all runtime sources to PAI_WORK_DIR
 mv ./* ${PAI_WORK_DIR}
