Add job exit code
Add job exit code

diff --git a/src/kube-runtime/src/runtime b/src/kube-runtime/src/runtime
--- a/src/kube-runtime/src/runtime
+++ b/src/kube-runtime/src/runtime
@@ -47,20 +47,27 @@ PAI_USER_LOG_FILE=${PAI_LOG_DIR}/user.pai.all
 source ${PAI_RUNTIME_DIR}/runtime_env.sh
 
 # check port conflict
-python ${PAI_RUNTIME_DIR}/port.py > >(tee -a ${PAI_LOG_DIR}/runtime.pai.stdout) 2> >(tee -a ${PAI_LOG_DIR}/runtime.pai.stderr >&2)
+python ${PAI_RUNTIME_DIR}/port.py > >(tee -a ${PAI_LOG_DIR}/runtime.pai.stdout) 2> >(tee -a ${PAI_LOG_DIR}/runtime.pai.stderr >&2) || exit $?
 
 # execute preCommands generated by plugin
-${PAI_RUNTIME_DIR}/precommands.sh > >(tee -a ${PAI_LOG_DIR}/runtime.pai.stdout) 2> >(tee -a ${PAI_LOG_DIR}/runtime.pai.stderr >&2)
+${PAI_RUNTIME_DIR}/precommands.sh > >(tee -a ${PAI_LOG_DIR}/runtime.pai.stdout) 2> >(tee -a ${PAI_LOG_DIR}/runtime.pai.stderr >&2) || exit $?
 
 # Put verbose output to user.pai.all, stdout to user.pai.stdout, stderr to user.pai.stderr
 # execute user commands
 # priority=100
-echo "[INFO] USER COMMAND START"
+echo "[INFO] USER COMMAND START" >> ${PAI_LOG_DIR}/user.pai.stderr
 ${PAI_RUNTIME_DIR}/user.sh > >(tee -a ${PAI_LOG_DIR}/user.pai.stdout ${PAI_USER_LOG_FILE}) 2> >(tee -a ${PAI_LOG_DIR}/user.pai.stderr ${PAI_USER_LOG_FILE} >&2) &
 USER_PID=$!
 
-echo "[INFO] USER COMMAND END"
 wait ${USER_PID}
+# return exit code for USER_PID if exit code not 0
+USER_EXIT_CODE=$?
+if [ ${USER_EXIT_CODE} -ne 0 ]; then
+  exit ${USER_EXIT_CODE}
+fi
+
+echo "[INFO] USER COMMAND END" >> ${PAI_LOG_DIR}/user.pai.stderr
 
 # execute postCommands generated by plugin
-${PAI_RUNTIME_DIR}/postcommands.sh > >(tee -a ${PAI_LOG_DIR}/runtime.pai.stdout) 2> >(tee -a ${PAI_LOG_DIR}/runtime.pai.stderr >&2)
+${PAI_RUNTIME_DIR}/postcommands.sh > >(tee -a ${PAI_LOG_DIR}/runtime.pai.stdout) 2> >(tee -a ${PAI_LOG_DIR}/runtime.pai.stderr >&2) || exit $?
+
